services:
  postgres:
    image: postgres:17
    container_name: guard-db
    restart: always
    environment:
      POSTGRES_USER: guard
      POSTGRES_PASSWORD: root
      POSTGRES_DB: guard
    ports:
      - "5434:5432"
    volumes:
      - guard-db-data:/var/lib/postgresql/data   # named volume

volumes:
  guard-db-data:
